package model

type MstClientId struct {
	ClientId                  string `json:"client_id"`
	ClientCd                  string `json:"client_cd"`
	AuditFlg                  string `json:"audit_flg"`
	Pwd                       string `json:"pwd"`
	NrFlg                     string `json:"nr_flg"`
	DbIp                      string `json:"db_ip"`
	FileDirPath               string `json:"file_dir_path"`
	DbIpGlobal                string `json:"db_ip_global"`
	DeFlg                     string `json:"de_flg"`
	DeAutoNoFlg               string `json:"de_auto_no_flg"`
	DeCsvDlFlg                string `json:"de_csv_dl_flg"`
	DeCondSaveFlg             string `json:"de_cond_save_flg"`
	DeDataSetFlg              string `json:"de_data_set_flg"`
	TmAutoNoFlg               string `json:"tm_auto_no_flg"`
	TmCsvDlFlg                string `json:"tm_csv_dl_flg"`
	TmCondSaveFlg             string `json:"tm_cond_save_flg"`
	TmDataSetFlg              string `json:"tm_data_set_flg"`
	TmAreaSearchFlg           string `json:"tm_area_search_flg"`
	TmDateCstFlg              string `json:"tm_date_cst_flg"`
	TmImgAtFlg                string `json:"tm_img_at_flg"`
	TmTaskActionFlg           string `json:"tm_task_action_flg"`
	TmDispMstFlg              string `json:"tm_disp_mst_flg"`
	TmMadridProtSetFlg        string `json:"tm_madrid_prot_set_flg"`
	LmFlg                     string `json:"lm_flg"`
	LmApiStatus               string `json:"lm_api_status"`
	LmApiIp                   string `json:"lm_api_ip"`
	MoUrlNumFlg               string `json:"mo_url_num_flg"`
	MoHisSavePeriodFlg        string `json:"mo_his_save_period_flg"`
	MoAutoGettingFlg          string `json:"mo_auto_getting_flg"`
	TimeStampUseFlg           string `json:"time_stamp_use_flg"`
	TimeStampLicenceFlg       string `json:"time_stamp_licence_flg"`
	TmElAppFlg                string `json:"tm_el_app_flg"`
	TmIpdlSyncFlg             string `json:"tm_ipdl_sync_flg"`
	DeHagueSetFlg             string `json:"de_hague_set_flg"`
	DnDateCstFlg              string `json:"dn_date_cst_flg"`
	DbName                    string `json:"db_name"`
	JsonIpArrow               string `json:"json_ip_arrow"`
	IpArrowFlg                string `json:"ip_arrow_flg"`
	LastPasswordChangeDays    string `json:"last_password_change_days"`
	LastPasswordChangeDaysFlg string `json:"last_password_change_days_flg"`
	LastPasswordChangeUnit    string `json:"last_password_change_unit"`
	SignUpFlg                 string `json:"sign_up_flg"`
	SignUpAuthKey             string `json:"sign_up_auth_key"`
	JsonDomainMail            string `json:"json_domain_mail"`
	NmMngUseFlag              string `json:"nm_mng_use_flag"`
	TmMngUseFlag              string `json:"tm_mng_use_flag"`
	WmMngUseFlag              string `json:"wm_mng_use_flag"`
	DbInstance                string `json:"db_instance"`
}
