steps:

########################
# op-rcvmapping
########################

- name: 'bash'
  args: ["mv", "-f", ".cloudbuild/conf/op-rcvmapping/prd/config.js", "services/op-rcvmapping/html/op/rcvmapping/js/"]

# build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
  '--tag=gcr.io/$PROJECT_ID/op-rcvmapping:master-$REVISION_ID', 
  '--file=services/op-rcvmapping/Dockerfile', "."]

# push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/op-rcvmapping:master-$REVISION_ID']

# deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'op-rcvmapping-dot-brights-bros',  '--command=', '--project=brights-bros', '--image=gcr.io/$PROJECT_ID/op-rcvmapping:master-$REVISION_ID', '--memory=256M', '--port=8000', '--cpu=1', '--timeout=900', '--platform=managed', '--allow-unauthenticated', '--region=asia-northeast1']

# policy
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'services', 'add-iam-policy-binding', '--project=brights-bros','--platform=managed', '--region=asia-northeast1', 'op-rcvmapping-dot-brights-bros', '--member=allUsers', '--role=roles/run.invoker']
