export const DEFAULT_LOCALE = "jp"
export const URL_API_JWT_VERIFY = "https://staging-dot-jwt-dot-brights-bros-uwt3euhkna-an.a.run.app/uapi/jwt/verify"
export const URL_API_JWT_SESSION = "https://staging-dot-jwt-dot-brights-bros-uwt3euhkna-an.a.run.app/uapi/jwt/session"
export const URL_API_RCVINV_LIST = "https://staging-dot-uapi-rcvinv-dot-brights-bros.an.r.appspot.com/uapi/op/rcvinv"
export const URL_API_USER_LOCALE = "https://staging-dot-api-user-dot-brights-bros.an.r.appspot.com/uapi/user/locale"
export const URL_API_MST_ADDRSET = "https://staging-dot-uapi-addrset-dot-brights-bros.an.r.appspot.com/uapi/mst/addrset"
export const URL_API_RCVMAPPING = "https://staging-dot-api-rcvmapping-addrset-dot-brights-bros.an.r.appspot.com/uapi/rcvmapping/addrset/set"
export const URL_API_RCVMAPPING_REMOVE = "https://staging-dot-api-rcvmapping-addrset-dot-brights-bros.an.r.appspot.com/uapi/rcvmapping/addrset/remove"